name: Deploy to EC2 with PEM key and Nginx fixes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        env:
          EC2_HOST: ec2-15-164-171-168.ap-northeast-2.compute.amazonaws.com # Your EC2 DNS

      - name: Connect to EC2 and execute deployment commands
        # Removed -i ~/.ssh/id_rsa
        # Updated 'ls' path for Amazon Linux/Nginx common setup
        # Corrected service name if Nginx is not 'nginx.service' or installed if needed
        run: |
          # The -t option is good to keep if you have 'sudo' commands.
          ssh -t ec2-user@${{ vars.EC2_HOST }} "
            # Check if /var/www/html exists, if not, use /usr/share/nginx/html
            # Or identify the correct path on your instance
            if [ -d '/var/www/html' ]; then
              ls -l /var/www/html;
            elif [ -d '/usr/share/nginx/html' ]; then
              ls -l /usr/share/nginx/html;
            else
              echo 'Neither /var/www/html nor /usr/share/nginx/html found. Please check path.';
              exit 1; # Fail the step if path is not found
            fi;

            # Check if Nginx is installed, install if not (example for Amazon Linux)
            # You might want to do this in a separate step or only once during setup
            if ! command -v nginx &> /dev/null; then
              echo 'Nginx not found, installing...';
              sudo yum update -y && sudo yum install nginx -y;
              sudo systemctl enable nginx; # Enable Nginx to start on boot
            fi;

            # Restart Nginx service (ensure the correct service name)
            # For Amazon Linux, it's typically 'nginx'
            sudo systemctl restart nginx;
            echo 'Nginx restarted successfully (or confirmed)';
          "
        env:
          EC2_USER: ec2-user # For Amazon Linux 2/2023
          EC2_HOST: ec2-15-164-171-168.ap-northeast-2.compute.amazonaws.com # Your EC2 DNS
