name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0 # Use the latest version
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 Host to known_hosts (important for first connection)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H your-ec2-instance-ip-or-dns >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        env:
          # Replace with your actual EC2 IP or DNS
          SSH_HOST: your-ec2-instance-ip-or-dns

      - name: Connect to EC2 and execute deployment commands
        # Add -t if your commands require a pseudo-terminal (e.g., sudo)
        # Remove -T if your commands need a pseudo-terminal
        # For deployment, often -T is fine or omitted, but if you need to run interactive commands, use -t
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip-or-dns "ls -l /var/www/html; sudo systemctl restart nginx"
        env:
          # Replace with your EC2 user and IP/DNS
          EC2_USER: ec2-user
          EC2_HOST: ec2-15-164-171-168.ap-northeast-2.compute.amazonaws.com
