name: Deploy to EC2 with PEM key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 Host to known_hosts
        # ALL these commands MUST be in the SAME 'run' block
        # and the EC2_HOST variable must be available for this step.
        run: |
          mkdir -p ~/.ssh
          # Use the environment variable here
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        env:
          # Define EC2_HOST here, or make sure it's a global var or job-level var
          EC2_HOST: ec2-15-164-171-168.ap-northeast-2.compute.amazonaws.com # Your EC2 DNS

      - name: Connect to EC2 and execute deployment commands
        # No -i ~/.ssh/id_rsa needed, agent handles it
        # -t is important for sudo
        run: |
          ssh -t "$EC2_USER"@"$EC2_HOST" "
            # Use 'sudo su -' for example if you need to switch to root for specific commands
            # Ensure paths are correct for your instance:
            if [ -d '/var/www/html' ]; then
              ls -l /var/www/html;
            elif [ -d '/usr/share/nginx/html' ]; then
              ls -l /usr/share/nginx/html;
            else
              echo 'Neither /var/www/html nor /usr/share/nginx/html found. Please check path.';
              exit 1;
            fi;

            # Ensure Nginx is installed and its service name is correct
            if ! command -v nginx &> /dev/null; then
              echo 'Nginx not found, attempting to install (Amazon Linux/RHEL/CentOS example)...';
              sudo yum update -y && sudo yum install nginx -y;
              sudo systemctl enable nginx;
            fi;

            sudo systemctl restart nginx;
            echo 'Nginx restart command sent.';
          "
        env:
          EC2_USER: ec2-user # For Amazon Linux 2/2023
          EC2_HOST: ec2-15-164-171-168.ap-northeast-2.compute.amazonaws.com # Your EC2 DNS
